# Generated by Django 2.1.2 on 2019-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_power', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='date_time',
            new_name='date_time_record',
        ),
        migrations.AlterField(
            model_name='power',
            name='power_consumption',
            field=models.IntegerField(max_length=10),
        ),
    ]
