# Generated by Django 2.1.2 on 2019-02-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_power', '0007_auto_20190201_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='date_time_record',
            field=models.DateTimeField(default='2019-02-01 17:37:04'),
        ),
    ]
