# Generated by Django 2.1.6 on 2019-02-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('light_power', '0008_auto_20190201_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='power',
            name='date_time_record',
            field=models.DateTimeField(default='2019-02-11 18:16:13'),
        ),
    ]
